apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: finops-ui-image
    newName: REPLACE_WITH_ECR_REGISTRY/financial/mas/finops-ui
    newTag: latest
