apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml

images:
  - name: teleport-app-service-image
    newName: REPLACE_WITH_ECR_REGISTRY/financial/mas/platform/teleport-app-service
    newTag: latest
