apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-alloy-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://internal-git-http.git.svc.cluster.local:3000/gitops/platform.git
    targetRevision: main
    path: helmChart/charts/alloy
    helm:
      valueFiles:
        - ../../alloy-service/values.yaml
  destination:
    name: financial-service-eks
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

