apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - peer-authentication.yaml
  - telemetry.yaml
  - generate-authorization-policy.yaml
  - kyverno-istio-rbac.yaml
  - add-ambient-label.yaml
