apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-alloy-ops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://internal-git-http.git.svc.cluster.local:3000/gitadmin/platform.git
    targetRevision: main
    path: helmChart/charts/alloy
    helm:
      valueFiles:
        - ../../alloy-ops/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

