apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller-service
  namespace: argocd
spec:
  project: ops-infra-project
  source:
    repoURL: http://internal-git-http.git.svc.cluster.local:3000/gitadmin/platform.git
    targetRevision: main
    path: helmChart/charts/aws-load-balancer-controller
    helm:
      valueFiles:
        - ../../aws-load-balancer-controller-service/values.yaml
  destination:
    # Service EKS: 이름(name) 기반 참조 (server URL 아님)
    name: financial-service-eks
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
