apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-monitoring-workloads
  namespace: argocd
spec:
  project: ops-infra-project
  source:
    repoURL: http://internal-git-http.git.svc.cluster.local:3000/gitadmin/platform.git
    targetRevision: main
    path: financial-ops-eks/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
