apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-config-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: ops-infra-project
  source:
    repoURL: http://internal-git-http.git.svc.cluster.local:3000/gitadmin/platform.git
    targetRevision: main
    path: financial-service-eks/eso-config
    kustomize: {}
  destination:
    name: financial-service-eks
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
