apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: ops-infra-project
  source:
    repoURL: http://internal-git-http.git.svc.cluster.local:3000/gitadmin/platform.git
    targetRevision: main
    path: helmChart/charts/external-secrets
    helm:
      valueFiles:
        - ../../external-secrets/values.yaml
  destination:
    # Service EKS: 이름(name) 기반 참조 (server URL 아님)
    name: financial-service-eks
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
