apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-mas
  namespace: argocd
spec:
  project: mas-workloads-project
  source:
    repoURL: http://internal-git-http.git.svc.cluster.local:3000/gitadmin/platform.git
    targetRevision: main
    path: financial-ops-eks/platform-mas
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-mas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
