apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teleport-app-service
  namespace: argocd
spec:
  project: ops-infra-project
  source:
    repoURL: http://internal-git-http.git.svc.cluster.local:3000/gitadmin/platform.git
    targetRevision: main
    path: financial-ops-eks/teleport-app-service
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: teleport-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
