apiVersion: v2
appVersion: 1.31.0
description: Temporal is a distributed, scalable, durable, and highly available orchestration
  engine to execute asynchronous long-running business logic in a scalable and resilient
  way.
home: https://temporal.io/
keywords:
- temporal
- workflow
- orchestration
maintainers:
- name: temporalio
  url: https://temporal.io/
name: temporal
sources:
- https://github.com/temporalio/temporal
type: application
version: 1.2.0