apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-loki
  namespace: argocd
spec:
  project: ops-infra-project
  source:
    repoURL: http://internal-git-http.git.svc.cluster.local:3000/gitadmin/platform.git
    targetRevision: main
    path: helmChart/charts/loki
    helm:
      valueFiles:
        - ../../loki/values.yaml
  destination:
    name: financial-ops-eks
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

