- import_playbook: service-istio-ambient.yml
- import_playbook: ops-internal-git.yml
- import_playbook: ops-argocd.yml
- import_playbook: service-cluster-access.yml
- import_playbook: cilium-install.yml
