apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-fqdn-eso
spec:
  description: "external-secrets → Secrets Manager VPC interface endpoint egress 허용"
  endpointSelector:
    matchLabels:
      io.kubernetes.pod.namespace: external-secrets
      app.kubernetes.io/name: external-secrets
  egress:
    - toEndpoints:
        - matchLabels:
            k8s-app: kube-dns
            io.kubernetes.pod.namespace: kube-system
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
          rules:
            dns:
              - matchPattern: "*.amazonaws.com"
    - toFQDNs:
        - matchName: "secretsmanager.ap-northeast-2.amazonaws.com"
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP